version: "2.30.0"
services:
  backend:
    image: krish124/educaseindiaassignment:latest
    restart: on-failure
    ports:
      - 5001:5001
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
