version: "3.8"

services:
  backend:
    image: krish124/educaseindiaassignment:latest
    restart: on-failure
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
