name: Deploy alma-nilokheri

on:
  push:
    branches:
      - main
jobs:
  backend:
    runs-on: ubuntu-latest
    environment: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make .env file for Backend
        run: |
          echo -e "DB_HOST=${{vars.DB_HOST}} \n DB_USER=${{vars.DB_USER}} \n DB_PASSWORD=${{vars.DB_PASS}} \n DB_NAME=${{vars.DB_NAME}}" > ./backend/.env

      - name: Read .env
        run: echo ./backend/.env

      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_KEY}}

      - name: Build Backend Docker Image
        run: docker build -t vishu7im/almanilokheri-backend ./backend

      - name: Publish Backend image to Docker Hub
        run: docker push vishu7im/almanilokheri-backend:latest

  deploy:
    runs-on: self-hosted
    needs:
      - backend
    steps:
      - name: Deploy to production
        run: |
         sudo docker-compose pull
         sudo docker-compose up -d
         sudo docker image prune -f

      - name: DONE
        run: echo "Deployment complete"
