name: Deploy Educase India Assignment

on:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    environment: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Make .env file for Backend
        run: |
          echo -e "DB_HOST=${{ secrets.DB_HOST }}\nDB_USER=${{ secrets.DB_USER }}\nDB_PASSWORD=${{ secrets.DB_PASS }}\nDB_NAME=${{ secrets.DB_NAME }}" > ./.env
          
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Backend Docker Image
        run: docker build -t krish124/educaseindiaassignment:latest .

      - name: Publish Backend image to Docker Hub
        run: docker push krish124/educaseindiaassignment:latest

  deploy:
    runs-on: self-hosted
    needs: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" -p ${{ secrets.DOCKER_PASSWORD }} --force

      - name: Deploy to production
        run: |
          # Ensure docker-compose.yml is in the root directory or specify the correct path
          sudo docker-compose pull
          sudo docker-compose up -d
          sudo docker image prune -f --filter "until=24h"

      - name: Notify on Success
        if: success()
        run: echo "🎉 Deployment successful!"
