name: Deploy Educase India Assignment

on:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    environment: backend
    steps:
      # Checkout the source code
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Node.js
      - name: Install Node.js 23
        uses: actions/setup-node@v2
        with:
          node-version: "23.3.0"

      # Create .env file for Backend
      - name: Make .env file for Backend
        run: |
          echo -e "DB_HOST=${{ secrets.DB_HOST }}\nDB_USER=${{ secrets.DB_USER }}\nDB_PASSWORD=${{ secrets.DB_PASS }}\nDB_NAME=${{ secrets.DB_NAME }}" > ./.env

      # Login to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t krish124/educaseindiaassignment:latest .
          docker push krish124/educaseindiaassignment:latest

  deploy:
    runs-on: self-hosted
    needs: backend
    steps:
      # Checkout the source code
      - name: Checkout code
        uses: actions/checkout@v4

      # Deploy with docker-compose
      - name: Deploy Application
        run: |
          sudo docker-compose pull
          sudo docker-compose up -d
          sudo docker image prune -f 

      # Notify on Success
      - name: Notify on Success
        if: success()
        run: echo "🎉 Deployment successful!"
